import { GameData } from "@game/game-common-types";

export const exampleIntroGameState: GameData = {
  settings: {
    numberOfCards: 25,
    startingTeam: "red",
    numberOfAssassins: 1,
  },
  state: {
    stage: "intro",
    cards: [
      { word: "intro", team: "red", selected: false },
      { word: "banana", team: "red", selected: false },
      { word: "cherry", team: "red", selected: false },
      { word: "dragon", team: "red", selected: false },
      { word: "elephant", team: "red", selected: false },
      { word: "fig", team: "red", selected: false },
      { word: "grape", team: "red", selected: false },
      { word: "hazelnut", team: "green", selected: false },
      { word: "kiwi", team: "green", selected: false },
      { word: "lemon", team: "red", selected: false },
      { word: "mango", team: "green", selected: false },
      { word: "nectarine", team: "green", selected: false },
      { word: "orange", team: "green", selected: false },
      { word: "papaya", team: "green", selected: false },
      { word: "quince", team: "green", selected: false },
      { word: "raspberry", team: "green", selected: false },
      { word: "strawberry", team: "assassin", selected: false },
      { word: "tangerine", team: "red", selected: false },
      { word: "umbrella", team: "bystander", selected: false },
      { word: "violet", team: "bystander", selected: false },
      { word: "watermelon", team: "bystander", selected: false },
      { word: "xylophone", team: "bystander", selected: false },
      { word: "yacht", team: "bystander", selected: false },
      { word: "zebra", team: "bystander", selected: false },
      { word: "avocado", team: "bystander", selected: false },
    ],
    rounds: [{ team: "red" }],
  },
  _id: "abc123!intro",
};

export const exampleCodemasterStage: GameData = {
  settings: {
    numberOfCards: 25,
    startingTeam: "red",
    numberOfAssassins: 1,
  },
  state: {
    stage: "codemaster",
    cards: [
      { word: "codemaster", team: "red", selected: false },
      { word: "banana", team: "red", selected: true },
      { word: "cherry", team: "red", selected: false },
      { word: "dragon", team: "red", selected: false },
      { word: "elephant", team: "red", selected: false },
      { word: "fig", team: "red", selected: false },
      { word: "grape", team: "red", selected: false },
      { word: "hazelnut", team: "green", selected: true },
      { word: "kiwi", team: "green", selected: false },
      { word: "lemon", team: "red", selected: false },
      { word: "mango", team: "green", selected: false },
      { word: "nectarine", team: "green", selected: false },
      { word: "orange", team: "green", selected: false },
      { word: "papaya", team: "green", selected: false },
      { word: "quince", team: "green", selected: false },
      { word: "raspberry", team: "green", selected: false },
      { word: "strawberry", team: "assassin", selected: false },
      { word: "tangerine", team: "red", selected: false },
      { word: "umbrella", team: "bystander", selected: false },
      { word: "violet", team: "bystander", selected: false },
      { word: "watermelon", team: "bystander", selected: false },
      { word: "xylophone", team: "bystander", selected: false },
      { word: "yacht", team: "bystander", selected: false },
      { word: "zebra", team: "bystander", selected: false },
      { word: "avocado", team: "bystander", selected: false },
    ],
    rounds: [{ team: "red" }],
  },
  _id: "abc123!codemaster",
};

export const exampleCodebreakerStage: GameData = {
  settings: {
    numberOfCards: 25,
    startingTeam: "red",
    numberOfAssassins: 1,
  },
  state: {
    stage: "codebreaker",
    cards: [
      { word: "codebreaker", team: "red", selected: false },
      { word: "banana", team: "red", selected: true },
      { word: "cherry", team: "red", selected: false },
      { word: "dragon", team: "red", selected: false },
      { word: "elephant", team: "red", selected: false },
      { word: "fig", team: "red", selected: false },
      { word: "grape", team: "red", selected: false },
      { word: "hazelnut", team: "green", selected: true },
      { word: "kiwi", team: "green", selected: false },
      { word: "lemon", team: "red", selected: false },
      { word: "mango", team: "green", selected: false },
      { word: "nectarine", team: "green", selected: false },
      { word: "orange", team: "green", selected: false },
      { word: "papaya", team: "green", selected: false },
      { word: "quince", team: "green", selected: false },
      { word: "raspberry", team: "green", selected: false },
      { word: "strawberry", team: "assassin", selected: false },
      { word: "tangerine", team: "red", selected: false },
      { word: "umbrella", team: "bystander", selected: false },
      { word: "violet", team: "bystander", selected: false },
      { word: "watermelon", team: "bystander", selected: false },
      { word: "xylophone", team: "bystander", selected: false },
      { word: "yacht", team: "bystander", selected: false },
      { word: "zebra", team: "bystander", selected: false },
      { word: "avocado", team: "bystander", selected: false },
    ],
    rounds: [
      { team: "red", codeword: "yellow", guessesAllowed: 3, guessedWords: [] },
    ],
  },
  _id: "abc123!codebreaker",
};

export const exampleGameOverStage: GameData = {
  settings: {
    numberOfCards: 25,
    startingTeam: "red",
    numberOfAssassins: 1,
  },
  state: {
    stage: "gameover",
    winner: "green",
    cards: [
      { word: "codebreaker", team: "red", selected: false },
      { word: "banana", team: "red", selected: true },
      { word: "cherry", team: "red", selected: false },
      { word: "dragon", team: "red", selected: false },
      { word: "elephant", team: "red", selected: true },
      { word: "fig", team: "red", selected: true },
      { word: "grape", team: "red", selected: true },
      { word: "hazelnut", team: "green", selected: true },
      { word: "kiwi", team: "green", selected: false },
      { word: "lemon", team: "red", selected: false },
      { word: "mango", team: "green", selected: true },
      { word: "nectarine", team: "green", selected: true },
      { word: "orange", team: "green", selected: false },
      { word: "papaya", team: "green", selected: false },
      { word: "quince", team: "green", selected: false },
      { word: "raspberry", team: "green", selected: false },
      { word: "strawberry", team: "assassin", selected: true },
      { word: "tangerine", team: "red", selected: false },
      { word: "umbrella", team: "bystander", selected: true },
      { word: "violet", team: "bystander", selected: false },
      { word: "watermelon", team: "bystander", selected: false },
      { word: "xylophone", team: "bystander", selected: false },
      { word: "yacht", team: "bystander", selected: false },
      { word: "zebra", team: "bystander", selected: true },
      { word: "avocado", team: "bystander", selected: false },
    ],
    rounds: [
      {
        team: "red",
        codeword: "yellow",
        guessesAllowed: 2,
        guessedWords: ["grape", "fig"],
      },
      {
        team: "green",
        codeword: "blah",
        guessesAllowed: 2,
        guessedWords: ["mango", "nectarine"],
      },
      {
        team: "red",
        codeword: "crazy",
        guessesAllowed: 3,
        guessedWords: ["grape", "tangerine", "umbrella"],
      },
      {
        team: "green",
        codeword: "stripey",
        guessesAllowed: 2,
        guessedWords: ["zebra"],
      },
      {
        team: "red",
        codeword: "stripey",
        guessesAllowed: 2,
        guessedWords: ["strawberry"],
      },
    ],
  },
  _id: "abc123!winner",
};
