import { GameData } from "@game/game-common-types";
export const exampleIntroGameState: GameData = {
  settings: {
    numberOfCards: 25,
    startingTeam: "red",
    numberOfAssassins: 1,
  },
  state: {
    stage: "intro",
    cards: [
      { word: "intro", selected: false },
      { word: "banana", selected: false },
      { word: "cherry", selected: false },
      { word: "dragon", selected: false },
      { word: "elephant", selected: false },
      { word: "fig", selected: false },
      { word: "grape", selected: false },
      { word: "hazelnut", selected: false },
      { word: "kiwi", selected: false },
      { word: "lemon", selected: false },
      { word: "mango", selected: false },
      { word: "nectarine", selected: false },
      { word: "orange", selected: false },
      { word: "papaya", selected: false },
      { word: "quince", selected: false },
      { word: "raspberry", selected: false },
      { word: "strawberry", selected: false },
      { word: "tangerine", selected: false },
      { word: "umbrella", selected: false },
      { word: "violet", selected: false },
      { word: "watermelon", selected: false },
      { word: "xylophone", selected: false },
      { word: "yacht", selected: false },
      { word: "zebra", selected: false },
      { word: "avocado", selected: false },
    ],
    rounds: [
      {
        team: "red",
        codeword: "",
        guessesAllowed: 0,
        turns: [],
      },
    ],
  },
  _id: "abc123!intro",
};

export const exampleCodemasterStage: GameData = {
  settings: {
    numberOfCards: 25,
    startingTeam: "red",
    numberOfAssassins: 1,
  },
  state: {
    stage: "codemaster",
    cards: [
      { word: "codemaster", team: "red", selected: false },
      { word: "banana", team: "red", selected: true },
      { word: "cherry", team: "red", selected: false },
      { word: "dragon", team: "red", selected: false },
      { word: "elephant", team: "red", selected: false },
      { word: "fig", team: "red", selected: false },
      { word: "grape", team: "red", selected: false },
      { word: "hazelnut", team: "green", selected: true },
      { word: "kiwi", team: "green", selected: false },
      { word: "lemon", team: "red", selected: false },
      { word: "mango", team: "green", selected: false },
      { word: "nectarine", team: "green", selected: false },
      { word: "orange", team: "green", selected: false },
      { word: "papaya", team: "green", selected: false },
      { word: "quince", team: "green", selected: false },
      { word: "raspberry", team: "green", selected: false },
      { word: "strawberry", team: "assassin", selected: false },
      { word: "tangerine", team: "red", selected: false },
      { word: "umbrella", team: "bystander", selected: false },
      { word: "violet", team: "bystander", selected: false },
      { word: "watermelon", team: "bystander", selected: false },
      { word: "xylophone", team: "bystander", selected: false },
      { word: "yacht", team: "bystander", selected: false },
      { word: "zebra", team: "bystander", selected: false },
      { word: "avocado", team: "bystander", selected: false },
    ],
    rounds: [{ team: "red" }],
  },
  _id: "abc123!codemaster",
};

export const exampleCodebreakerStage: GameData = {
  settings: {
    numberOfCards: 25,
    startingTeam: "red",
    numberOfAssassins: 1,
  },
  state: {
    stage: "codebreaker",
    cards: [
      { word: "codebreaker", selected: false },
      { word: "banana", selected: true },
      { word: "cherry", selected: false },
      { word: "dragon", selected: false },
      { word: "elephant", selected: false },
      { word: "fig", selected: false },
      { word: "grape", selected: false },
      { word: "hazelnut", selected: true },
      { word: "kiwi", selected: false },
      { word: "lemon", selected: false },
      { word: "mango", selected: false },
      { word: "nectarine", selected: false },
      { word: "orange", selected: false },
      { word: "papaya", selected: false },
      { word: "quince", selected: false },
      { word: "raspberry", selected: false },
      { word: "strawberry", selected: false },
      { word: "tangerine", selected: false },
      { word: "umbrella", selected: false },
      { word: "violet", selected: false },
      { word: "watermelon", selected: false },
      { word: "xylophone", selected: false },
      { word: "yacht", selected: false },
      { word: "zebra", selected: false },
      { word: "avocado", selected: false },
    ],
    rounds: [{ team: "red", codeword: "yellow", guessesAllowed: 3, turns: [] }],
  },
  _id: "abc123!codebreaker",
};

export const exampleCodebreakerStageCorrectTeamCard: GameData = {
  settings: {
    numberOfCards: 25,
    startingTeam: "red",
    numberOfAssassins: 1,
  },
  state: {
    stage: "codebreaker",
    cards: [
      { word: "codebreaker", selected: false },
      { word: "banana", team: "red", selected: true },
      { word: "cherry", selected: false },
      { word: "dragon", selected: false },
      { word: "elephant", selected: false },
      { word: "fig", selected: false },
      { word: "grape", selected: false },
      { word: "hazelnut", selected: true },
      { word: "kiwi", selected: false },
      { word: "lemon", selected: false },
      { word: "mango", selected: false },
      { word: "nectarine", selected: false },
      { word: "orange", selected: false },
      { word: "papaya", selected: false },
      { word: "quince", selected: false },
      { word: "raspberry", selected: false },
      { word: "strawberry", selected: false },
      { word: "tangerine", selected: false },
      { word: "umbrella", selected: false },
      { word: "violet", selected: false },
      { word: "watermelon", selected: false },
      { word: "xylophone", selected: false },
      { word: "yacht", selected: false },
      { word: "zebra", selected: false },
      { word: "avocado", selected: false },
    ],
    rounds: [
      {
        team: "red",
        codeword: "yellow",
        guessesAllowed: 3,
        turns: [{ guessedWord: "banana", outcome: "CORRECT_TEAM_CARD" }],
      },
    ],
  },
  _id: "abc123!codebreaker",
};

export const exampleGameOverStage: GameData = {
  settings: {
    numberOfCards: 25,
    startingTeam: "red",
    numberOfAssassins: 1,
  },
  state: {
    stage: "gameover",
    winner: "green",
    cards: [
      { word: "codebreaker", selected: false, team: "red" },
      { word: "banana", selected: true, team: "red" },
      { word: "cherry", selected: false, team: "green" },
      { word: "dragon", selected: false, team: "bystander" },
      { word: "elephant", selected: true, team: "green" },
      { word: "fig", selected: true, team: "red" },
      { word: "grape", selected: true, team: "green" },
      { word: "hazelnut", selected: true, team: "bystander" },
      { word: "kiwi", selected: false, team: "assassin" },
      { word: "lemon", selected: false, team: "red" },
      { word: "mango", selected: true, team: "green" },
      { word: "nectarine", selected: true, team: "red" },
      { word: "orange", selected: false, team: "bystander" },
      { word: "papaya", selected: false, team: "red" },
      { word: "quince", selected: false, team: "green" },
      { word: "raspberry", selected: false, team: "bystander" },
      { word: "strawberry", selected: true, team: "red" },
      { word: "tangerine", selected: false, team: "green" },
      { word: "umbrella", selected: true, team: "bystander" },
      { word: "violet", selected: false, team: "red" },
      { word: "watermelon", selected: false, team: "green" },
      { word: "xylophone", selected: false, team: "red" },
      { word: "yacht", selected: false, team: "bystander" },
      { word: "zebra", selected: true, team: "green" },
      { word: "avocado", selected: false, team: "bystander" },
    ],
    rounds: [
      {
        team: "red",
        codeword: "yellow",
        guessesAllowed: 2,
        turns: [
          { guessedWord: "grape", outcome: "CORRECT_TEAM_CARD" },
          { guessedWord: "fig", outcome: "CORRECT_TEAM_CARD" },
        ],
      },
      {
        team: "green",
        codeword: "blah",
        guessesAllowed: 2,
        turns: [
          { guessedWord: "mango", outcome: "CORRECT_TEAM_CARD" },
          { guessedWord: "nectarine", outcome: "CORRECT_TEAM_CARD" },
        ],
      },
      {
        team: "red",
        codeword: "crazy",
        guessesAllowed: 3,
        turns: [
          { guessedWord: "grape", outcome: "OTHER_TEAM_CARD" },
          { guessedWord: "tangerine", outcome: "BYSTANDER_CARD" },
          { guessedWord: "umbrella", outcome: "BYSTANDER_CARD" },
        ],
      },
      {
        team: "green",
        codeword: "stripey",
        guessesAllowed: 2,
        turns: [{ guessedWord: "zebra", outcome: "CORRECT_TEAM_CARD" }],
      },
      {
        team: "red",
        codeword: "stripey",
        guessesAllowed: 2,
        turns: [{ guessedWord: "strawberry", outcome: "CORRECT_TEAM_CARD" }],
      },
    ],
  },
  _id: "abc123!winner",
};
