import { TEAM, STAGE } from "@game/game-common-constants";

export const expectedGameDataDefault = {
  settings: { numberOfCards: 25, startingTeam: TEAM.RED, numberOfAssassins: 1 },
  state: {
    stage: STAGE.INTRO,
    cards: [
      { word: "word1", team: TEAM.RED, selected: false },
      { word: "word2", team: TEAM.RED, selected: false },
      { word: "word3", team: TEAM.RED, selected: false },
      { word: "word4", team: TEAM.RED, selected: false },
      { word: "word5", team: TEAM.RED, selected: false },
      { word: "word6", team: TEAM.RED, selected: false },
      { word: "word7", team: TEAM.RED, selected: false },
      { word: "word8", team: TEAM.RED, selected: false },
      { word: "word9", team: TEAM.RED, selected: false },
      { word: "word10", team: TEAM.GREEN, selected: false },
      { word: "word11", team: TEAM.GREEN, selected: false },
      { word: "word12", team: TEAM.GREEN, selected: false },
      { word: "word13", team: TEAM.GREEN, selected: false },
      { word: "word14", team: TEAM.GREEN, selected: false },
      { word: "word15", team: TEAM.GREEN, selected: false },
      { word: "word16", team: TEAM.GREEN, selected: false },
      { word: "word17", team: TEAM.GREEN, selected: false },
      { word: "word18", team: TEAM.ASSASSIN, selected: false },
      { word: "word19", team: TEAM.BYSTANDER, selected: false },
      { word: "word20", team: TEAM.BYSTANDER, selected: false },
      { word: "word21", team: TEAM.BYSTANDER, selected: false },
      { word: "word22", team: TEAM.BYSTANDER, selected: false },
      { word: "word23", team: TEAM.BYSTANDER, selected: false },
      { word: "word24", team: TEAM.BYSTANDER, selected: false },
      { word: "word25", team: TEAM.BYSTANDER, selected: false },
    ],
    rounds: [
      {
        team: TEAM.RED,
        turns: [],
      },
    ],
  },
};

export const expectedGameDataCustom = {
  settings: {
    numberOfCards: 30,
    startingTeam: TEAM.GREEN,
    numberOfAssassins: 2,
  },
  state: {
    stage: STAGE.INTRO,
    cards: [
      { word: "word1", team: TEAM.GREEN, selected: false },
      { word: "word2", team: TEAM.GREEN, selected: false },
      { word: "word3", team: TEAM.GREEN, selected: false },
      { word: "word4", team: TEAM.GREEN, selected: false },
      { word: "word5", team: TEAM.GREEN, selected: false },
      { word: "word6", team: TEAM.GREEN, selected: false },
      { word: "word7", team: TEAM.GREEN, selected: false },
      { word: "word8", team: TEAM.GREEN, selected: false },
      { word: "word9", team: TEAM.GREEN, selected: false },
      { word: "word10", team: TEAM.RED, selected: false },
      { word: "word11", team: TEAM.RED, selected: false },
      { word: "word12", team: TEAM.RED, selected: false },
      { word: "word13", team: TEAM.RED, selected: false },
      { word: "word14", team: TEAM.RED, selected: false },
      { word: "word15", team: TEAM.RED, selected: false },
      { word: "word16", team: TEAM.RED, selected: false },
      { word: "word17", team: TEAM.RED, selected: false },
      { word: "word18", team: TEAM.RED, selected: false },
      { word: "word19", team: TEAM.RED, selected: false },
      { word: "word20", team: TEAM.ASSASSIN, selected: false },
      { word: "word21", team: TEAM.ASSASSIN, selected: false },
      { word: "word22", team: TEAM.BYSTANDER, selected: false },
      { word: "word23", team: TEAM.BYSTANDER, selected: false },
      { word: "word24", team: TEAM.BYSTANDER, selected: false },
      { word: "word25", team: TEAM.BYSTANDER, selected: false },
      { word: "word26", team: TEAM.BYSTANDER, selected: false },
      { word: "word27", team: TEAM.BYSTANDER, selected: false },
      { word: "word28", team: TEAM.BYSTANDER, selected: false },
      { word: "word29", team: TEAM.BYSTANDER, selected: false },
      { word: "word30", team: TEAM.BYSTANDER, selected: false },
    ],
    rounds: [
      {
        team: TEAM.GREEN,
        turns: [],
      },
    ],
  },
};
